### ISSUE TITLE
Different templates for CLI

### ISSUE THREAD

**Issue by knowbody** [knowbody/crra#15]
I'd like to copy CRA a bit here, and create different templates for reason react apps.

1. Keep something very basic as a main script: `yarn create reason-react-app MyApp`
would create very basic setup which is not confusing for the beginners and doesn't overwhelm them. Somewhere where you can just jump in and try out Reason code.

2. Another thing is a bit more complex config, @tzilist has a great PR for CSS Modules and Service worker here #7 

3. And more...

4. The one that interests me the most is the Reason React future/experimental where we could be exploring the new API for Reason React

Would love to hear more thoughts on this one?

**Comment by gilbert** [comment]
I maintain a [project generator](https://github.com/Concatapult/pult) that sakes a slightly different approach. Instead of having different versions of boilerplates, it instead *always* generates a minimal boilerplate, and then enables you to add pieces on top via a cli. For example:

```
$ pult new my-proj
```

will get you a minimal boilerplate. After that you're free to choose which "path" you want to take by adding the modules relevant to your project. Some examples would be:

- `pult add react`
- `pult add knex`
- `pult add cookie-session`

and so on.

I would love to see something like this for ReasonML / BuckleScript, or even to put our efforts together and collaborate on creating a single project generator to rule them all :)

**Comment by knowbody** [comment]
added via #23
