### ISSUE TITLE
Reason-CLI install failing during crra project initialisation

### ISSUE THREAD

**Issue by Verlet64** [knowbody/crra#38]
## Expected Behaviour

create-reason-react-app successfully builds a project

## Observed Behaviour

When installing reason-cli, it errors but doesn't terminate immediately. When it eventually terminates, it dumps out a lot (_a lot_) of this error into the console.

```
{{directory}}/{{project_name}}/node_modules/reason-cli/rel/node_modules/.cache/_esy/build-eject/bin/fastreplacestring.exe: Syntax error: word unexpected (expecting ")")
```
## Environment and Reproducing

Ubuntu 16.04
yarn 0.24.6
node 8.1.2
npm 5.0.3

## Potential Fix

I am of the understanding that the inclusion of reason-cli was pretty recent? In any case, using the dev bundle url in the package.json instead of the url for the binary works. Looking at reason-cli it may have something to do with the dev bundles building from source? 

Thanks!

**Comment by knowbody** [comment]
thanks for reporting, mind sending PR with the fix?

**Comment by asolove** [comment]
I think the problem is that the [package.json](https://github.com/knowbody/crra/blob/8e44ad4a83bbe277064719de31462a97da0024f7/templates/basic/package.json#L45) requires the Mac-specific version of reason-cli.

I don't know of a way to specify different versions of a package based on the user's platform, so we could try:
- including manual install steps in the README so people can recover from the failed install
- publishing reason-cli under different platform-specific names, then adding them all to the optionalDeps list and hoping at least one succeeds on each install.

I'm happy to help with either, but wanted to get advice on the right strategy first.

**Comment by chenglou** [comment]
Heyo, we've all moved to https://github.com/reasonml-community/reason-scripts. So this problem no longer exists.

Sorry for the delay and thanks for reporting this!
